### PR TITLE
Speed

### PR DESCRIPTION
**Pull request by kbarbary**
This changes most (but not yet all) of our FFT operations to use PyFFTW. With this change, I see speed boosts of a factor of 6+ in both `atm.evaluate_galaxy()` and `atm.evaluate_point_source()`. Total runtime is about 4 min. Profiling shows that the main steps take the following amount of time:

- `fit_galaxy_single`: 5s
- `fit_galaxy_multi`: 13s
- `fit_position_sn_sky_multi`: 222s (89%)

The final step just takes a really long time to converge (14 iterations, ~150 function calls), much more than the `fit_galaxy_*` functions. Also, the final gradient and chisq don't look very good. Maybe l_bfgs_b is not a good optimizer for this part of the problem? Or more probably there's probably a bug...

### CODE REVIEW

**Comment by cmsaunders** [comment]
There is definitely a bug. The final fit no longer finds anything that looks like a sn. I'll see if I can find any obvious issues.

**Comment by kbarbary** [comment]
Sorry! :)

**Comment by cmsaunders** [comment]
I don't know if this has a big enough effect to be the bug, but the only
issue I have found is that in the galaxy/point source evaluate function,
the adr term is not being added to the offset. I would try fixing this, but
I think I don't understand the adr part enough in the new code.

**Comment by kbarbary** [comment]
In the refactor, I realized that the ADR and convolution can be combined into a single array, since both are fixed. Both terms are factored into `self.fftconv`. You can see how the ADR is put into this array in `AtmModel.__init__()`.

Did you add any logging output code? If so, push it and I'll try to use it to debug it myself. Or we can do it next time we get together. I'll also try to write some unit tests (which I should have worked on before this pyFFTW performance stuff!).

**Comment by cmsaunders** [comment]
I did add logging code, and just pushed it. It just makes a dictionary with
data, atms, and sub-dictionaries with the results of the fit at three
points: after fitting the master ref, after fitting all the final refs, and
after fitting the non-refs. These dictionaries each have the galaxy, sky,
snctr, ctrs, and sn at that point.

The dictionary is saved in the data directory (need to change that) as
DDT_output.pkl. run scripts/ddt-plot DDT_output.pkl to see the model and
residual at each step (need to add labels to plot though.)

**Pull request merged**
